apiVersion: apps/v1
kind: Deployment
metadata:
  name: bw-notifications
  namespace: bitwarden
spec:
  strategy: 
    type: Recreate
  replicas: 1  
  selector:
    matchLabels:
      app: bw-notifications
  template:
    metadata:
      labels:
        app: bw-notifications
    spec: 
      containers:
      - name: bw-notifications
        image: bitwarden/notifications
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 5000
        envFrom:
         - configMapRef:
            name: bw-config 
        volumeMounts:
        - name: certs
          mountPath: /etc/bitwarden/ca-certificates     
        - name: logs
          mountPath: /etc/bitwarden/logs                          
      volumes:
      - name: certs
        nfs:
          server: 10.43.42.45
          path: /bwdata/ca-certificates                    
      - name: logs
        nfs:
          server: 10.43.42.45
          path: /bwdata/logs/notifications     
---
apiVersion: v1
kind: Service
metadata:
  name: notifications
  namespace: bitwarden
spec:
  selector:
    app: bw-notifications
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000                