apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
  namespace: bitwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  namespace: bitwarden
spec:
  replicas: 1
  selector:
     matchLabels:
       app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql
        image: bitwarden/mssql
        resources:
          requests:
            memory: "1G"
            cpu: "500m"
          limits:
            memory: "2G"
            cpu: "1000m"
        ports:
        - containerPort: 1433
        envFrom:
         - configMapRef:
            name: bw-config 
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: bitwarden
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433