apiVersion: apps/v1
kind: Deployment
metadata:
  name: bw-admin
  namespace: bitwarden
spec:
  strategy: 
    type: Recreate
  replicas: 1  
  selector:
    matchLabels:
      app: bw-admin
  template:
    metadata:
      labels:
        app: bw-admin
    spec: 
      containers:
      - name: bw-admin
        image: bitwarden/admin
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: globalSettings__internalidentityKey
          valueFrom:
            secretKeyRef:
              name: web
              key: globalSettings__internalIdentityKey
        volumeMounts:
        - name: core
          mountPath: /etc/bitwarden/core
        - name: certs
          mountPath: /etc/bitwarden/ca-certificates     
        - name: logs
          mountPath: /etc/bitwarden/logs                          
      volumes:
      - name: core
        nfs:
          server: 10.43.235.63
          path: /core
      - name: certs
        nfs:
          server: 10.43.235.63
          path: /ca-certificates                    
      - name: logs
        nfs:
          server: 10.43.235.63
          path: /logs/admin         