apiVersion: apps/v1
kind: Deployment
metadata:
  name: bw-setup
  namespace: bitwarden
spec:
  strategy: 
    type: Recreate
  replicas: 1  
  selector:
    matchLabels:
      app: bw-setup
  template:
    metadata:
      labels:
        app: bw-setup
    spec: 
      containers:
      - name: bw-setup
        image: bitwarden/setup
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: globalSettings__internalIdentityKey
          valueFrom:
            secretKeyRef:
              name: web
              key: globalSettings__internalIdentityKey
        volumeMounts:
        - name: setup
          mountPath: /
      volumes:
      - name: setup
        nfs:
          server: 10.43.235.63
          path: /bitwarden
        # persistentVolumeClaim:
          # claimName: bitwarden-app-data