# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: api-data
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: api-certs
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bw-api
  namespace: bitwarden
spec:
  selector:
    matchLabels:
      app: bw-api
  template:
    metadata:
      labels:
        app: bw-api
    spec:
      nodeSelector:
        disktype: shared
      containers:
      - name: bw-api
        image: bitwarden/api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: api
          mountPath: /etc/bitwarden/core 
        - name: certs
          mountPath: /etc/bitwarden/ca-certificates                   
      volumes:
      - name: api
        persistentVolumeClaim:
          claimName: bitwarden-data
      - name: certs
        persistentVolumeClaim:
          claimName: bitwarden-certs        