apiVersion: apps/v1
kind: Deployment
metadata:
  name: bw-attachments
  namespace: bitwarden
spec:
  selector:
    matchLabels:
      app: bw-attachments
  template:
    metadata:
      labels:
        app: bw-attachments
    spec:
      containers:
      - name: bw-attachments
        image: bitwarden/attachments
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 5000
        envFrom:
         - configMapRef:
            name: bw-config      
        volumeMounts:
        - name: attachments
          mountPath: /etc/bitwarden/core/attachments
      volumes:
      - name: attachments
        nfs:
          server: 10.43.42.45
          path: /bwdata/core/attachments
---          
apiVersion: v1
kind: Service
metadata:
  name: attachments
  namespace: bitwarden
spec:
  selector:
    app: bw-attachments
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000              