apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv1
  namespace: bitwarden
spec:
  storageClassName: "nfs"
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/"
    server: nfs-server
